### ISSUE TITLE
Please add a title

### ISSUE THREAD

**Issue by puranjayjain** [beerjs/jaipur#1]
Please add the following title to the repo -> Jaipur, India

**Comment by jordanpapaleo** [comment]
You should have write access to this repo. 

Sent from my iPhone

On Apr 7, 2016, at 5:17 AM, Puranjay Jain notifications@github.com wrote:

Please add the following title to the repo -> Jaipur, India

**Comment by puranjayjain** [comment]
@jordanpapaleo I don't think I have write access to change the title of the page since it is written as 'No description or website provided.'

**Comment by jordanpapaleo** [comment]
I'll take a look shortly.

**Comment by jordanpapaleo** [comment]
Done

**Comment by puranjayjain** [comment]
@jordanpapaleo thanks a lot :beers:
